INHERIT: docs/common/config.yml

site_name: "Q"
site_url: "https://cycfi.github.io/q"
site_description: "Q Documentation"

repo_name: "cycfi/q"
repo_url: "https://github.com/cycfi/q"
copyright: |
  Copyright &copy; 2014-2023 Joel de Guzman. All rights reserved.
  Distributed under the
  <a href="https://opensource.org/licenses/MIT">MIT License</a></p>

extra:
  social:
  - icon: "fontawesome/brands/github"
    link: "https://github.com/cycfi/q/"
    name: "Cycfi Q on GitHub"

  - icon: "fontawesome/brands/discord"
    link: "https://discord.gg/4MymV4EaY5"
    name: "Cycfi on Discord"

  - icon: "fontawesome/brands/facebook"
    link: "https://www.facebook.com/groups/cycfi/"
    name: "Cycfi on Facebook"

# theme:
#   logo: "assets/images/q.svg"
#   favicon: "assets/images/favicon.ico"

nav:
- "index.md"
- "api.md"
- "design.md"
- "fundamentals.md"
- "hello_universe.md"
- "hello_world.md"
- "setup.md"
- "using_fx.md"
